inherit_gem:
  rubocop-discourse: default.yml

AllCops:
  TargetRubyVersion: "3.2"
  Exclude:
    - 'bin/*'
    - 'gemfiles/**/*'
    - 'vendor/**/*'

Discourse/Plugins/NoMonkeyPatching:
  Enabled: false

Discourse/Plugins/NamespaceMethods:
  Exclude:
    - exe/prometheus_exporter

Style/InvertibleUnlessCondition:
  Exclude:
    - '*.gemspec' 
